// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTaskDomain.Concrete;

#nullable disable

namespace TestTaskDomain.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220703040448_tet")]
    partial class tet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TestTaskDomain.Models.CompanySubdivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CompanySubdivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanySubdivisionId");

                    b.ToTable("CompanySubdivisions");
                });

            modelBuilder.Entity("TestTaskDomain.Models.CompanySubdivision", b =>
                {
                    b.HasOne("TestTaskDomain.Models.CompanySubdivision", null)
                        .WithMany("ChildSubdivisions")
                        .HasForeignKey("CompanySubdivisionId");
                });

            modelBuilder.Entity("TestTaskDomain.Models.CompanySubdivision", b =>
                {
                    b.Navigation("ChildSubdivisions");
                });
#pragma warning restore 612, 618
        }
    }
}
